# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39f8776bc7ab7fe4289bd8875678751aa2a883599d91c2f025392c1436478a9c89371593ba836640656846808bf507f2f3a9869dd5376d3ea8f7333563d82128

test:
  secret_key_base: 70278a807533e1d85c5ae0daff7d1ba262dcbbaf1fb8b7f0a1bb114adbc2759f5190be73576e56ba4559ca9ef27203506b4940e71c12370307d0b785c1cfacc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
